let musics = [
    "国语/Super Star.mp3",
    "国语/You Better Not Think About Me.mp3",
    "国语/下雨天.mp3",
    "国语/不將就 (電影_何以笙簫默_片尾曲).mp3",
    "国语/中国话.mp3",
    "国语/你不是真正的快樂.mp3",
    "国语/你的微笑.mp3",
    "国语/來自天堂的魔鬼.mp3",
    "国语/倒帶.mp3",
    "国语/倒數.mp3",
    "国语/光.mp3",
    "国语/光年之外 (電影 《Passengers》 中國區主題曲).mp3",
    "国语/关不上的窗.mp3",
    "国语/再見.mp3",
    "国语/凉城.mp3",
    "国语/分手總要在雨天.mp3",
    "国语/句號.mp3",
    "国语/只要平凡 (電影《我不是藥神 》主題曲).mp3",
    "国语/吻別.mp3",
    "国语/喜歡你.mp3",
    "国语/因為愛情.mp3",
    "国语/天空沒有極限.mp3",
    "国语/天黑黑 - Remastered.mp3",
    "国语/奇妙能力歌.mp3",
    "国语/好久不見.mp3",
    "国语/孤勇者 - 《英雄聯盟_雙城之戰》動畫劇集中文主題曲.mp3",
    "国语/小半.mp3",
    "国语/小幸運.mp3",
    "国语/小情歌.mp3",
    "国语/屋頂.mp3",
    "国语/布拉格廣場.mp3",
    "国语/很久以後 - 電影《可不可以，你也剛好喜歡我》主題曲.mp3",
    "国语/後來的我們.mp3",
    "国语/情歌.mp3",
    "国语/愛, 很簡單.mp3",
    "国语/愛丫愛丫.mp3",
    "国语/愛你.mp3",
    "国语/愛的主打歌.mp3",
    "国语/我以為.mp3",
    "国语/我想更懂你.mp3",
    "国语/我愛他.mp3",
    "国语/我的歌声里 (You Exist In My Song).mp3",
    "国语/我的秘密 (MySecret).mp3",
    "国语/手心的薔薇.mp3",
    "国语/日不落.mp3",
    "国语/易燃易爆炸.mp3",
    "国语/最美的期待.mp3",
    "国语/期待愛.mp3",
    "国语/本草綱目.mp3",
    "国语/李白.mp3",
    "国语/模特.mp3",
    "国语/歐若拉.mp3",
    "国语/流沙.mp3",
    "国语/浪人琵琶.mp3",
    "国语/淘汰.mp3",
    "国语/滴答.mp3",
    "国语/為你寫詩.mp3",
    "国语/猜不透.mp3",
    "国语/玻璃心.mp3",
    "国语/當你.mp3",
    "国语/白月光与朱砂痣.mp3",
    "国语/稻香.mp3",
    "国语/空空如也.mp3",
    "国语/突然想起你.mp3",
    "国语/第一次愛的人.mp3",
    "国语/紅塵客棧.mp3",
    "国语/紅玫瑰(國).mp3",
    "国语/紅豆.mp3",
    "国语/綠光.mp3",
    "国语/背對背擁抱.mp3",
    "国语/蒲公英的約定.mp3",
    "国语/親愛的那不是愛情.mp3",
    "国语/記事本.mp3",
    "国语/說愛你.mp3",
    "国语/說散就散.mp3",
    "国语/起风了 - 电视剧_加油你是最棒的_主题曲.mp3",
    "国语/越长大越孤单.mp3",
    "国语/踏山河.mp3",
    "国语/过客.mp3",
    "国语/過火.mp3",
    "国语/遺失的心跳.mp3",
    "国语/遺失的美好.mp3",
    "国语/那年夏天寧靜的海.mp3",
    "国语/青花瓷.mp3",
    "国语/風中有朵雨做的雲.mp3",
    "国语/體面.mp3",
    "国语/麻雀.mp3",
    "小众/不分手的恋爱.mp3",
    "小众/后会无期.mp3",
    "小众/坏女孩 - Remix版.mp3",
    "小众/坏女孩.mp3",
    "小众/客官不可以 - Remix版.mp3",
    "小众/海绵宝宝.mp3",
    "小众/犯贱.mp3",
    "小众/红装.mp3",
    "小众/芊芊.mp3",
    "小众/苦笑.mp3",
    "日韩/Butter-Fly (デジモンアドベンチャー全話OP).mp3",
    "日韩/Dream lantern.mp3",
    "日韩/Kokoronashi.mp3",
    "日韩/LOSER.mp3",
    "日韩/MY ALL.mp3",
    "日韩/only my railgun.mp3",
    "日韩/SAKURA.mp3",
    "日韩/ありがとう.mp3",
    "日韩/さくら 〜あなたに出会えてよかった〜.mp3",
    "日韩/カタオモイ.mp3",
    "日韩/ピースサイン - Peace Sign.mp3",
    "日韩/ヤキモチ.mp3",
    "日韩/光るなら.mp3",
    "日韩/冬のエピローグ.mp3",
    "日韩/千本桜.mp3",
    "日韩/君が好きだと叫びたい.mp3",
    "日韩/心做し.mp3",
    "日韩/怪物.mp3",
    "日韩/打上花火.mp3",
    "日韩/星屑ビーナス.mp3",
    "日韩/海の幽霊.mp3",
    "日韩/灰色と青 ( + 菅田将暉 ).mp3",
    "日韩/生きていたんだよな.mp3",
    "日韩/紅蓮華.mp3",
    "英文/...Baby One More Time.mp3",
    "英文/A Little Love.mp3",
    "英文/A Thousand Miles.mp3",
    "英文/Always Remember Us This Way.mp3",
    "英文/Anyone of Us (Stupid Mistake).mp3",
    "英文/As Long as You Love Me.mp3",
    "英文/Bad Romance.mp3",
    "英文/Be What You Wanna Be.mp3",
    "英文/Beat It.mp3",
    "英文/Because Of You.mp3",
    "英文/Big Big World.mp3",
    "英文/Centuries.mp3",
    "英文/Cry on My Shoulder.mp3",
    "英文/Diamonds.mp3",
    "英文/Do You Hear The People Sing_.mp3",
    "英文/Dragostea Din Tei - W&W Remix.mp3",
    "英文/Dying in the Sun.mp3",
    "英文/Everytime We Touch.mp3",
    "英文/Far Away from Home.mp3",
    "英文/Fight Song.mp3",
    "英文/Firework.mp3",
    "英文/Flowers.mp3",
    "英文/Free Loop.mp3",
    "英文/God Is A Girl.mp3",
    "英文/Hall of Fame (feat. will.i.am).mp3",
    "英文/Halo.mp3",
    "英文/Hotel California - 2013 Remaster.mp3",
    "英文/I Believe I Can Fly.mp3",
    "英文/I Could Be The One.mp3",
    "英文/If I Were a Boy.mp3",
    "英文/Innocence.mp3",
    "英文/It's My Life.mp3",
    "英文/Judas.mp3",
    "英文/Just Dance.mp3",
    "英文/Just Give Me a Reason (feat. Nate Ruess).mp3",
    "英文/Love Paradise.mp3",
    "英文/Moonlight Shadow.mp3",
    "英文/My Heart Will Go On - Love Theme from _Titanic_.mp3",
    "英文/My Love Will Get You Home.mp3",
    "英文/Nothing's Gonna Change My Love for You.mp3",
    "英文/Only Love.mp3",
    "英文/Only Time.mp3",
    "英文/Pretty Boy.mp3",
    "英文/Price Tag.mp3",
    "英文/Rain On Me (with Ariana Grande).mp3",
    "英文/Rave Love.mp3",
    "英文/Roar.mp3",
    "英文/Rolling in the Deep.mp3",
    "英文/Seasons in the Sun.mp3",
    "英文/Shape of You.mp3",
    "英文/Stay Here Forever.mp3",
    "英文/Take Me Hand (Acoustic).mp3",
    "英文/Take Me to Your Heart.mp3",
    "英文/Telephone.mp3",
    "英文/The Cup of Life (The Official Song of the World Cup, France '98) - Remix - English Radio Edit.mp3",
    "英文/The Day You Went Away.mp3",
    "英文/Valder Fields.mp3",
    "英文/Viva La Vida.mp3",
    "英文/We Will Rock You - Remastered 2011.mp3",
    "英文/What Are Words (feat. Peter Hollens & Evynne Hollens).mp3",
    "英文/What Are Words.mp3",
    "英文/When You're Gone.mp3",
    "英文/Wonderful U - Demo Version.mp3",
    "英文/Yesterday Once More.mp3",
    "英文/You Raise Me Up.mp3",
    "英文/You're Beautiful.mp3",
    "飞车/Gangsta Bop.mp3",
    "飞车/Gee.mp3",
    "飞车/Girlfriend.mp3",
    "飞车/Have A Nice Day.mp3",
    "飞车/In the End.mp3",
    "飞车/Insomnia.mp3",
    "飞车/Let U Go.mp3",
    "飞车/Love Story.mp3",
    "飞车/Loves Me Not.mp3",
    "飞车/Numb.mp3",
    "飞车/Poker Face.mp3",
    "飞车/Remember the Name (feat. Styles of Beyond).mp3",
    "飞车/Right Now (Na Na Na).mp3",
    "飞车/Sick enough to die (Feat. JAMIE).mp3",
    "飞车/Sk8er Boi.mp3",
    "飞车/Something's Going On.mp3",
    "飞车/Whiskey In The Jar.mp3",
    "飞车/Your Love Is My Drug.mp3"
];

let count = 0;
let maxCount = 0;
let basePath = "https://githcc.github.io/music_self_mp3/";
musics = musics.map(item=>basePath+item);
let musicsNow = musics;